---
deployment:
  tasks:
    - export APPPATH=/home/akifulla/
    - export DEPLOYPATH=/home/akifulla/public_html

    # Install Composer dependencies
    - /opt/cpanel/composer/bin/composer install --no-dev --optimize-autoloader --working-dir=$APPPATH

    # Deploy public folder
    - /bin/rsync -av --delete $APPPATH/public/ $DEPLOYPATH/

    # Symlink storage
    - /bin/ln -sf $APPPATH/storage/app/public $DEPLOYPATH/storage

    # Set permissions
    - /bin/chmod -R 775 $APPPATH/storage $APPPATH/bootstrap/cache

    # Clear and cache Laravel config/routes/views
    - php $APPPATH/artisan config:clear
    - php $APPPATH/artisan cache:clear
    - php $APPPATH/artisan route:clear
    - php $APPPATH/artisan view:clear
    - php $APPPATH/artisan config:cache
    - php $APPPATH/artisan route:cache
